// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG1agXXChpD5pyzRIo6UIn-YLVelsqvdA',
    appId: '1:810535262210:web:1bcc7a4d787bb36902af1b',
    messagingSenderId: '810535262210',
    projectId: 'parkins-care',
    authDomain: 'parkins-care.firebaseapp.com',
    storageBucket: 'parkins-care.firebasestorage.app',
    measurementId: 'G-0V6G6CH7FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8SF0gHYOazPQgTBsmdHyTe1NiFdgffE0',
    appId: '1:810535262210:android:9e97c2841334e6ba02af1b',
    messagingSenderId: '810535262210',
    projectId: 'parkins-care',
    storageBucket: 'parkins-care.firebasestorage.app',
  );
}
